package com.fiveGame.entity;

import java.io.Serializable;

public class Admin implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.aname
     *
     * @mbggenerated
     */
    private String aname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.apass
     *
     * @mbggenerated
     */
    private String apass;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.aname
     *
     * @return the value of admin.aname
     *
     * @mbggenerated
     */
    public String getAname() {
        return aname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.aname
     *
     * @param aname the value for admin.aname
     *
     * @mbggenerated
     */
    public void setAname(String aname) {
        this.aname = aname == null ? null : aname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.apass
     *
     * @return the value of admin.apass
     *
     * @mbggenerated
     */
    public String getApass() {
        return apass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.apass
     *
     * @param apass the value for admin.apass
     *
     * @mbggenerated
     */
    public void setApass(String apass) {
        this.apass = apass == null ? null : apass.trim();
    }
}