package com.fiveGame.entity;

import java.io.Serializable;

public class Room implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.roomname
     *
     * @mbggenerated
     */
    private String roomname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.roomnum
     *
     * @mbggenerated
     */
    private Integer roomnum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.roomname
     *
     * @return the value of room.roomname
     *
     * @mbggenerated
     */
    public String getRoomname() {
        return roomname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.roomname
     *
     * @param roomname the value for room.roomname
     *
     * @mbggenerated
     */
    public void setRoomname(String roomname) {
        this.roomname = roomname == null ? null : roomname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.roomnum
     *
     * @return the value of room.roomnum
     *
     * @mbggenerated
     */
    public Integer getRoomnum() {
        return roomnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.roomnum
     *
     * @param roomnum the value for room.roomnum
     *
     * @mbggenerated
     */
    public void setRoomnum(Integer roomnum) {
        this.roomnum = roomnum;
    }
}